### ISSUE TITLE
I have error while update existing theme

### ISSUE THREAD

**Issue by nikhil2evolution** [XMPieLab/uStore-NG#2]
Hello
Please see following error while i update existing theme

Custom theme cannot have prefix "XMPie"

I want to add copyright message in footer so i have download and update footer.js file when i upload then give error message

Please help me

Thanks in Advance

**Comment by seinavco** [comment]
Hi,

You cannot publish a theme with the prefix 'XMPie'. It is reserved to XMPie out of the box themes.
 
What is your 'publish' command?

Einav

**Comment by nikhil2evolution** [comment]
Hello
I am new to react.
so how can i find publish command and how can i publish ??
Thanks in advance

**Comment by nikhil2evolution** [comment]
In AquaBlue theme just, i want to add copyright text in footer

**Comment by seinavco** [comment]
Please look at our wiki. This page explain how to publish a theme:
https://github.com/XMPieLab/uStore-NG/wiki/Publishing-the-theme

**Comment by nikhil2evolution** [comment]
Thanks...

**Comment by seinavco** [comment]
From the wiki, this is our publish command for new theme:
npm run publish -- name=<themeName> displayName='<displayName>'

Dont use the 'XMPie' prefix.

**Comment by nikhil2evolution** [comment]
Thanks for your support
I have uploaded theme in ustore
Thanks
