### ISSUE TITLE
Open the src\routes\index.scss file and add the following

### ISSUE THREAD

**Issue by westdigitalfr** [XMPieLab/uStore-NG#4]
Hello,

You wrote

> 6. Open the src\routes\index.scss file and add the following:

I am unable to find such a file in my src/routes folder.
Instead, there's an

> index.js

file, whose contents seems to fit with the rest of your article.

Did I miss something, of should your article mention "index.js" instead of "index.scss"?

Thanks!

**Comment by snirrotem** [comment]
Hi @westdigitalfr 

you are correct, the referance should be to index.js and not index.scss.

fixing it now.

thanks
